# "key": "YOUR_API_KEY"
# "369623": "BEATMAPSET_ID"# (FOR OVERRIDES ONLY; LEAVE EMPTY TO USE API VALUES)
#   "creator": "SINGLE_CREATOR_NAME"
#   "creator":
#   -  "LIST_OF_CREATORS"
#   -  "or use 'et al.'"
#   "artist": "ARTIST_NAME"
#   "title": "SONG_TITLE"
"key": ""
"369623":
  "creator":
  -  "clayton"
  -  "mangomizer"
  -  "kaifin"
  "artist": "Cool Dude"
  "title": "Nice Title"
"227021":
  "creator":
  -  "MegaApple_Pi"
  -  "et al."
  "artist": "Artist Goes Here"
  "title": "Title Goes Here"
"89429":
  "creator":
  -  "peppy"
  -  "Ephemeral"
